/**
 * Peregrine CMS - Vue 3 Page Renderer
 * Component Build Script
 */

import { rollup } from 'rollup'
import vue from '@vitejs/plugin-vue'
import { nodeResolve } from '@rollup/plugin-node-resolve'
import esbuild from 'rollup-plugin-esbuild'
import postcss from 'rollup-plugin-postcss'
import fs from 'fs'
import path from 'path'

const felibName = process.argv[2]
if (!felibName) {
  console.error('Usage: node buildvue3.js <felib-name>')
  process.exit(1)
}

console.log('========== Building Vue 3 Components ==========')
console.log('FeLib:', felibName)

const basePath = './src/main/content/jcr_root/apps'
const distBasePath = `./target/classes/etc/felibs/${felibName}`

function pathToComponentName(filePath) {
  const normalized = filePath.replace(/\\/g, '/')
  const appsIndex = normalized.indexOf('/apps/')
  if (appsIndex === -1) return null
  
  const afterApps = normalized.slice(appsIndex + 6)
  const parts = afterApps.split('/')
  parts.pop()
  
  return parts.join('-').toLowerCase()
}

function toModuleName(componentName) {
  const parts = componentName.split('-')
  const camelCase = parts.map((part, i) => 
    part.charAt(0).toUpperCase() + part.slice(1)
  ).join('')
  return 'cmp' + camelCase
}

function findVueFiles(dir, files = []) {
  if (!fs.existsSync(dir)) {
    console.log('Directory not found:', dir)
    return files
  }
  
  const items = fs.readdirSync(dir)
  
  for (const item of items) {
    const fullPath = path.join(dir, item)
    const stat = fs.statSync(fullPath)
    
    if (stat.isDirectory()) {
      findVueFiles(fullPath, files)
    } else if (item.endsWith('.vue')) {
      files.push(fullPath)
    }
  }
  
  return files
}

function mkdirSync(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

async function compileComponent(filePath) {
  const componentName = pathToComponentName(filePath)
  const moduleName = toModuleName(componentName)
  
  console.log(`Compiling: ${filePath}`)
  console.log(`  Component: ${componentName}`)
  console.log(`  Module: ${moduleName}`)
  
  try {
    const cssOutputPath = path.join(distBasePath, 'css', `${componentName}.css`)
    
    const bundle = await rollup({
      input: filePath,
      plugins: [
        vue({
          template: {
            compilerOptions: {
              whitespace: 'condense'
            }
          },
          style: {
            postcssPlugins: []
          }
        }),
        postcss({
          extract: cssOutputPath,
          minimize: process.env.NODE_ENV === 'production'
        }),
        nodeResolve(),
        esbuild({
          target: 'es2020',
          minify: process.env.NODE_ENV === 'production'
        })
      ],
      external: ['vue'],
      onwarn(warning, warn) {
        if (warning.code === 'THIS_IS_UNDEFINED') return
        if (warning.message && warning.message.includes('sourcemap')) return
        warn(warning)
      }
    })
    
    const outputFile = path.join(distBasePath, 'js', `${componentName}.js`)
    
    await bundle.write({
      format: 'iife',
      name: moduleName,
      file: outputFile,
      globals: { vue: 'Vue' },
      banner: `/* Peregrine CMS - Vue 3 Component: ${componentName} */`
    })
    
    await bundle.close()
    
    console.log(`  Output: ${outputFile}`)
    return { success: true, name: componentName, moduleName }
    
  } catch (error) {
    console.error(`  Error: ${error.message}`)
    return { success: false, name: componentName, error: error.message }
  }
}

function generateIndexFiles() {
  const jsDir = path.join(distBasePath, 'js')
  if (fs.existsSync(jsDir)) {
    const jsFiles = fs.readdirSync(jsDir)
      .filter(f => f.endsWith('.js'))
      .map(f => `js/${f}`)
    
    fs.writeFileSync(
      path.join(distBasePath, 'js.txt'),
      '# Auto-generated by buildvue3.js\n' + jsFiles.join('\n')
    )
    console.log(`Generated js.txt with ${jsFiles.length} files`)
  }
  
  const cssDir = path.join(distBasePath, 'css')
  if (fs.existsSync(cssDir)) {
    const cssFiles = fs.readdirSync(cssDir)
      .filter(f => f.endsWith('.css'))
      .map(f => `css/${f}`)
    
    if (cssFiles.length > 0) {
      fs.writeFileSync(
        path.join(distBasePath, 'css.txt'),
        '# Auto-generated by buildvue3.js\n' + cssFiles.join('\n')
      )
      console.log(`Generated css.txt with ${cssFiles.length} files`)
    }
  }
}

async function main() {
  console.log('Working directory:', process.cwd())
  
  mkdirSync(path.join(distBasePath, 'js'))
  mkdirSync(path.join(distBasePath, 'css'))
  
  const vueFiles = findVueFiles(basePath)
  console.log(`Found ${vueFiles.length} Vue component(s)\n`)
  
  if (vueFiles.length === 0) {
    console.log('No Vue files found.')
    return
  }
  
  const results = []
  for (const file of vueFiles) {
    const result = await compileComponent(file)
    results.push(result)
    console.log('')
  }
  
  generateIndexFiles()
  
  const successful = results.filter(r => r.success).length
  const failed = results.filter(r => !r.success).length
  
  console.log('========== Build Complete ==========')
  console.log(`Successful: ${successful}`)
  console.log(`Failed: ${failed}`)
  
  if (failed > 0) {
    process.exit(1)
  }
}

main().catch(err => {
  console.error('Build failed:', err)
  process.exit(1)
})
