/**
 * Peregrine CMS - Vue 3 Page Renderer
 * Component Build Script
 * 
 * Compiles Vue 3 SFCs to JavaScript modules.
 * Usage: node ../scripts/buildvue3.js pagerendervue3
 * Run from ui.apps directory
 */

import { rollup } from 'rollup'
import vue from '@vitejs/plugin-vue'
import { nodeResolve } from '@rollup/plugin-node-resolve'
import esbuild from 'rollup-plugin-esbuild'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const felibName = process.argv[2]
if (!felibName) {
  console.error('Usage: node buildvue3.js <felib-name>')
  process.exit(1)
}

console.log('========== Building Vue 3 Components ==========')
console.log('FeLib:', felibName)

// Paths relative to ui.apps directory (where npm run is executed)
const basePath = './src/main/content/jcr_root/apps'
const distBasePath = `./target/classes/etc/felibs/${felibName}`

function pathToCamelCase(filePath) {
  const relativePath = filePath.slice(basePath.length + 1)
  const parts = relativePath.split(path.sep)
  parts.pop() // Remove template.vue
  
  return parts
    .map((part, i) => i === 0 ? part.toLowerCase() : part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('')
}

function toModuleName(camelCase) {
  return 'cmp' + camelCase.charAt(0).toUpperCase() + camelCase.slice(1)
}

function findVueFiles(dir, files = []) {
  if (!fs.existsSync(dir)) {
    console.log('Directory not found:', dir)
    return files
  }
  
  const items = fs.readdirSync(dir)
  
  for (const item of items) {
    const fullPath = path.join(dir, item)
    const stat = fs.statSync(fullPath)
    
    if (stat.isDirectory()) {
      findVueFiles(fullPath, files)
    } else if (item.endsWith('.vue')) {
      files.push(fullPath)
    }
  }
  
  return files
}

function mkdirSync(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

async function compileComponent(filePath) {
  const nameCamelCase = pathToCamelCase(filePath)
  const moduleName = toModuleName(nameCamelCase)
  
  console.log(`Compiling: ${filePath}`)
  console.log(`  -> ${moduleName}`)
  
  try {
    const bundle = await rollup({
      input: filePath,
      plugins: [
        vue({
          template: {
            compilerOptions: {
              whitespace: 'condense'
            }
          }
        }),
        nodeResolve(),
        esbuild({
          target: 'es2020',
          minify: process.env.NODE_ENV === 'production'
        })
      ],
      external: ['vue'],
      onwarn(warning, warn) {
        if (warning.code === 'THIS_IS_UNDEFINED') return
        warn(warning)
      }
    })
    
    const outputFile = path.join(distBasePath, 'js', `${nameCamelCase}.js`)
    
    await bundle.write({
      format: 'iife',
      name: moduleName,
      file: outputFile,
      globals: { vue: 'Vue' },
      banner: `/* Peregrine CMS - Vue 3 Component: ${nameCamelCase} */`
    })
    
    await bundle.close()
    
    console.log(`  -> Written to ${outputFile}`)
    return { success: true, name: nameCamelCase, moduleName }
    
  } catch (error) {
    console.error(`  Error compiling ${filePath}:`, error.message)
    return { success: false, name: nameCamelCase, error: error.message }
  }
}

function generateIndexFiles() {
  const jsDir = path.join(distBasePath, 'js')
  if (fs.existsSync(jsDir)) {
    const jsFiles = fs.readdirSync(jsDir)
      .filter(f => f.endsWith('.js'))
      .map(f => `js/${f}`)
    
    fs.writeFileSync(
      path.join(distBasePath, 'js.txt'),
      '# Auto-generated by buildvue3.js\n' + jsFiles.join('\n')
    )
    console.log(`Generated js.txt with ${jsFiles.length} files`)
  }
}

async function main() {
  console.log('Working directory:', process.cwd())
  console.log('Looking for Vue files in:', basePath)
  
  // Create output directories
  mkdirSync(path.join(distBasePath, 'js'))
  mkdirSync(path.join(distBasePath, 'css'))
  
  // Find all Vue files
  const vueFiles = findVueFiles(basePath)
  console.log(`Found ${vueFiles.length} Vue component(s)`)
  
  if (vueFiles.length === 0) {
    console.log('No Vue files found. Check that the path is correct.')
    return
  }
  
  // Compile each component
  const results = []
  for (const file of vueFiles) {
    const result = await compileComponent(file)
    results.push(result)
  }
  
  // Generate index files
  generateIndexFiles()
  
  // Summary
  const successful = results.filter(r => r.success).length
  const failed = results.filter(r => !r.success).length
  
  console.log('\n========== Build Complete ==========')
  console.log(`Successful: ${successful}`)
  console.log(`Failed: ${failed}`)
  
  if (failed > 0) {
    console.log('\nFailed components:')
    results.filter(r => !r.success).forEach(r => {
      console.log(`  - ${r.name}: ${r.error}`)
    })
    process.exit(1)
  }
}

main().catch(err => {
  console.error('Build failed:', err)
  process.exit(1)
})
